# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PartyUp Registration' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PartyUp Registration
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/AdMob'
  pod ‘Cosmos’, ‘~>10.0’

  target 'PartyUp RegistrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PartyUp RegistrationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
